---
- hosts: ubuntu
  vars_files:
    - ./config.yaml
  roles:
    - nagios1
    - nagios2
    - nagios3
    - elastic1
    - grafana1
    - lamp1

- hosts: centos
  roles:
    - elastic2
    - grafana2
    - lamp2
