---
# tasks file for lamp1
- name: install apache
  apt:
    name: apache2
    state: latest
    update_cache: yes

- name: add apache_index
  copy:
    content: "Hello World"
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  register: apache_index

- name: start apache2 service
  service:
    name: apache2
    state: restarted
    enabled: yes
  when: apache_index.changed

- name: whitelist apache2 in ufw
  ufw:
    rule: allow
    port: '80'
    protocol: tcp

- name: install mysql-server
  apt:
    name: mysql-server
    state: latest
    update_cache: yes

- name: add mysql_index
  copy:
    content: 'Hi World'
    dest: /var/www/html/index1.html
    owner: root
    group: root
    mode: '0644'
  register: mysql_index

- name: install php
  apt:
    name:
      - php
      - php-mysql
      - libapache2-mod-php
    state: latest
    update_cache: yes

- name: add php_index
  copy:
    content: "Justine Flores"
    dest: /var/www/html/index2.html
    owner: root
    group: root
    mode: '0644'
