---
# tasks file for roles/python
- name: Install Python3 and pip3
  apt:
    name:
      - python3
      - python3-pip

    status: latest


- name: Use pip3 as default pip
  shell: update-alternatives --install /usr/bin/pip pip /user/bin/pip3 1

- name: Use python3 as default python
  shell: update-alternatives --install /usr/bin/python python /user/bin/python3 2
