---
# tasks file for lamp2
- name: install httpd
  yum:
    name: httpd
    state: latest
    update_cache: yes

- name: add httpd_index
  copy:
    content: "Madelo"
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  registeR: httpd

- name: start httpd
  service:
    name: httpd
    state: started
  when: httpd.changed

- name: stop firewalld
  service:
    name: firewalld
    state: stopped

- name: install mariadb
  yum:
    name: mariadb-server
    state: latest
    update_cache: yes

- name: add mysql_index
  copy:
    content: "FLORES"
    dest: /var/www/html/index1.html
    owner: root
    group: root
    mode: '0644'
  register: mysql

- name: start mariadb
  serivce:
    name: mariadb
    state: started
  when: mysql.changed

- name: install php
  yum:
    name:
      - php
      - php-mydsqlnd
    state: latest
    update_cache: yes

- name: add php index
  copy:
    content: "Flores"
    dest: /var/www/html/index2.html
    owner: root
    group: root
    mode: '0644'
  register: php

- name: restart httpd
  service:
    name: httpd
    state: restarted
  when: php.changed
