---
# tasks file for elastic2
- name: install pre-requisite of elastickstack
  yum:
    name: java-11-openjdk-level
    state: present
    update_cache: yes

- name: install elasticsearch repo
  yum_repository:
    name: Elastic_7.x.repo
    baseurl: https://artifacts.elastic.co/package/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
    description: Elastic 7.x repo

- name: Install Elasticsearch gpg key
  rpm_key:
    key: https://artifacs.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Install Elastic search
  yum:
    name: elasticsearch
    state: present
    update_cache: yes

- name: update config file to allow access
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host:'
    line: 'network.hosts: localhost'

- name: update config file
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'http.port:'
    line: 'http.port: 9200'

- name: start elasticsearch
  service:
    name: elasticsearch
    state: started

- name: install logstash repository
  yump_repository:
    name: Elastic repository for 7.x package
    baseurl: https://artifacts.elastic.co/package/7.x/yum
    gpgchecl: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: yes
    description: Elastic 7.x package repo

- name: install logstash
  yum:
    name: logstash
    state: present
    update_cache: yes

- name: update config file
  lineinfile:
    path: /etc/logstash/logstash.yml
    regexp: 'http.host:'
    line: 'http.host: 192.168.0.1'

- name: start logstash
  service:
    name: logstash
    state: started

- name: install kibana
  yum:
    name: kibana
    state: latest
    update_cache: yes

- name: update config file
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: 'server.host'
    line: 'server.host: 0.0.0.0'

- name: update config file
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: 'server.port:'
    line: 'server.port: 5601'

- name: update config file
  lineinfile:
    path: /etc/kibana.yml
    regexp: 'elasticsearch.hosts:'
    line: 'elasticsearch.hosts: ["http://localhost:9200"]'

- name: start kibana
  service:
    name: kibana
    state: started

- name: start logstash
  service:
    name: logstash
    state: started
